<a href="javascript:{}" target="_blank"
   onclick="document.getElementById('eTailAppForm').submit();return false;">
    <div style="display: flex;margin-bottom: 15px">
        <img src="<?php echo $this->getViewFileUrl('') ?>/images/sync_card.png"
             style="width:18%"/>
        <div style="width: 82%;   display: inline-block;    color: #616060;    padding: 11px;font-weight: bold;margin:auto">Promotional Financing available for 12 Months*
            with your Synchrony HOME Credit Card.
        </div>
    </div>
</a>
<div class="pre-approval-button-acima-credit-container" style="margin-bottom: 18px">
    <a href="https://www.snapfinance.com"
       target="_blank">
        <img src="<?php echo $this->getViewFileUrl('') ?>/images/snapfinance.jpeg"
             alt="Snap Finance - Apply Here"
             style="box-shadow:4px 2px 6px #010101; border: none;width:100%;height:100%"
             height="80" width="646"/>
    </a>
</div>